
services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - db
    networks:
      - app_net

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_net

  mock_people_service:
    build:
      context: ./scripts/mock-people-service
      dockerfile: Dockerfile
    ports:
      - "8081:3000"
    restart: on-failure
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net:
    driver: bridge
