// Code generated by ogen, DO NOT EDIT.

package people_service

// InfoGetBadRequest is response for InfoGet operation.
type InfoGetBadRequest struct{}

func (*InfoGetBadRequest) infoGetRes() {}

// InfoGetInternalServerError is response for InfoGet operation.
type InfoGetInternalServerError struct{}

func (*InfoGetInternalServerError) infoGetRes() {}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/People
type People struct {
	Name       string    `json:"name"`
	Surname    string    `json:"surname"`
	Patronymic OptString `json:"patronymic"`
	Address    string    `json:"address"`
}

// GetName returns the value of Name.
func (s *People) GetName() string {
	return s.Name
}

// GetSurname returns the value of Surname.
func (s *People) GetSurname() string {
	return s.Surname
}

// GetPatronymic returns the value of Patronymic.
func (s *People) GetPatronymic() OptString {
	return s.Patronymic
}

// GetAddress returns the value of Address.
func (s *People) GetAddress() string {
	return s.Address
}

// SetName sets the value of Name.
func (s *People) SetName(val string) {
	s.Name = val
}

// SetSurname sets the value of Surname.
func (s *People) SetSurname(val string) {
	s.Surname = val
}

// SetPatronymic sets the value of Patronymic.
func (s *People) SetPatronymic(val OptString) {
	s.Patronymic = val
}

// SetAddress sets the value of Address.
func (s *People) SetAddress(val string) {
	s.Address = val
}

func (*People) infoGetRes() {}
