// Code generated by ogen, DO NOT EDIT.

package people_service

import (
	"net/http"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// InfoGetParams is parameters of GET /info operation.
type InfoGetParams struct {
	PassportSerie  int
	PassportNumber int
}

func unpackInfoGetParams(packed middleware.Parameters) (params InfoGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "passportSerie",
			In:   "query",
		}
		params.PassportSerie = packed[key].(int)
	}
	{
		key := middleware.ParameterKey{
			Name: "passportNumber",
			In:   "query",
		}
		params.PassportNumber = packed[key].(int)
	}
	return params
}

func decodeInfoGetParams(args [0]string, argsEscaped bool, r *http.Request) (params InfoGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: passportSerie.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "passportSerie",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.PassportSerie = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "passportSerie",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: passportNumber.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "passportNumber",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.PassportNumber = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "passportNumber",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
