definitions:
  main.requestAddUser:
    properties:
      passportNumber:
        type: string
    type: object
  main.responseAddUser:
    properties:
      user:
        $ref: '#/definitions/model.User'
    type: object
  model.User:
    properties:
      address:
        type: string
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
      passportSerie:
        type: integer
      passwortNumber:
        type: integer
      patronymic:
        type: string
      surname:
        type: string
      updatedAt:
        type: string
    type: object
  validator.Validator:
    properties:
      errors:
        items:
          type: string
        type: array
      fieldErrors:
        additionalProperties:
          type: string
        type: object
    type: object
info:
  contact: {}
paths:
  /status:
    get:
      consumes:
      - application/json
      description: Check if the server is up and running
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Server Status
      tags:
      - api
  /users:
    post:
      consumes:
      - application/json
      description: Add new user
      parameters:
      - description: Passport serie and number
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/main.requestAddUser'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.responseAddUser'
        "400":
          description: Bad request input
          schema:
            type: object
        "422":
          description: Invalid input data
          schema:
            $ref: '#/definitions/validator.Validator'
        "500":
          description: Internal server error
          schema:
            type: object
      summary: Add User
      tags:
      - users
swagger: "2.0"
